### ISSUE TITLE
Possible way of picking up on undead mobs

### ISSUE THREAD

**Issue by Sunconure11** [TheIllusiveC4/Consecration#1]
A lot of undead mobs are classified under a creature attribute enum named `EnumCreatureAttribute.UNDEAD`. Why not use this to pick up on modded undead, or at least, try and pick up on them a bit easier?

**Comment by TheIllusiveC4** [comment]
Don't I do that already?

This is where I check for the applicable creatures to cancel death:
https://github.com/TheIllusiveC4/Consecration/blob/163c6bb8ec57908feba3e66512250aa8eba20c63/src/main/java/c4/consecration/common/EventHandlerCommon.java#L109

Which leads to this method in the EntityLivingBase class:
`public boolean isEntityUndead()
    {
        return this.getCreatureAttribute() == EnumCreatureAttribute.UNDEAD;
    }`

**Comment by TheIllusiveC4** [comment]
It's been a little over a week so if there's nothing to be corrected, I'll go ahead and close this issue. Please let me know if I've misunderstood anything.
