### ISSUE TITLE
(Compatibility) Buggy Interaction with EvilCraft's Vengeance Spirits

### ISSUE THREAD

**Issue by TechnoMysterio** [TheIllusiveC4/Consecration#10]
A compatibility issue with EvilCraft and this mod arises with the former's Vengeance Spirits. In order to progress at later points in EvilCraft, you need to use a specific item to kill them, and they cannot be killed in any other way. However, Consecration doesn't allow that, as Vengeance Spirits are classed as undead mobs, and they can technically only be killed by holy items, which cannot be done as they can only be affected by the special EvilCraft item.

The simplest way to fix this would be to blacklist Vengeance Spirits as undead mobs.

**Comment by TheIllusiveC4** [comment]
This certainly would be a problem. I'll try and figure out the best way to fix this.

**Comment by TechnoMysterio** [comment]
I'm not sure, but I think it might also mean that Spirits don't despawn, as they should die after a little while after they appear, and they might be immune to that due to them being classed as undead.

**Comment by TheIllusiveC4** [comment]
This mod doesn't prevent undead from despawning, only from dying due to damage. If these Spirits just die off on their own, there shouldn't be any interference from this mod.

**Comment by TechnoMysterio** [comment]
Ah, fair enough, I was just concerned that it might lead to lag problems if hordes of invisible spirits never actually despawned.
