### ISSUE TITLE
feature request holy water

### ISSUE THREAD

**Issue by Varg95** [TheIllusiveC4/Consecration#12]
I would like to request a holy water block/fluid. It heals you and normal mobs but kills of undead. its also a way to make potions just clicking it with a bottle gives you the holy water potion.

**Comment by TheIllusiveC4** [comment]
I'm definitely looking into adding some sort of holy water.

**Comment by wenlfs** [comment]
This also could be used to allow the weapons/tools smite the undeads without enchantments or fire. Using holy water to blessy the weapon/tool so dealing the standard damage and being able to kill the undead. To nerf it only non-enchanted weapons/tools could be combined with holy water.

I believe that it could be a good addition too.
