### ISSUE TITLE
support for Electroblob's Wizardry

### ISSUE THREAD

**Issue by Varg95** [TheIllusiveC4/Consecration#13]
It would be nice if whe could kill undead when whe use spells/wands from Electroblob's Wizardry.

**Comment by TheIllusiveC4** [comment]
Alright, I'll look into it.

**Comment by TheIllusiveC4** [comment]
It looks like Electroblob's Wizardry doesn't really add any holy spells, only fire spells. As far as the fire spells go, as long as they indicate fire damage then it should integrate naturally with the newest version of Consecration (0.0.8) that will be released pending Curse approval.
