### ISSUE TITLE
Request: Add a way for modders to register new kinds of damage as Holy

### ISSUE THREAD

**Issue by falkreon** [TheIllusiveC4/Consecration#15]
I have some holy damage in my mod (Magic Arsenal) and would like to indicate that to Consecration. It seems like it'd be cleanest to accept IMCs to mark certain categories, such as "heldWeapon", "damageSource", and "potion", and retain those in registry lists so that deaths can be allowed when they match. A registry would also make configuration or minetweaker support much easier, and most of the issues I see here would be solved.

Wanted to open the discussion before a PR, but let me know if you'd be interested in a PR for something like this.

**Comment by TheIllusiveC4** [comment]
Don't open a PR, because I'm planning to do some rewrites to the code base once I begin work on this mod again. I will take this suggestion into consideration though, it does sound like it could solve a lot of issues.
