### ISSUE TITLE
Angel of Vengence compatability not working right

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Consecration#17]
It could be that I'm just doing something wrong, but while I was testing in a modpack I'm making, I found that using the Offensive Caster's attacks will do damage to undead, but don't seem to smite them, meaning they continue regenerating health instantly, and presumably take less damage from those attacks.
The config has "holy" damage set by default, but is there anything else I have to do to get the compatability functioning?

On a related note, it would be useful to explain in the config file which mods are supported by default and don't need to be put into the config manually (I.E. Rin's Enchantments, which I presume don't need to be put into the config in order to function correctly due to the built-in compatability)

**Comment by IdrisQe** [comment]
I tried all of them. From what I could tell, none activated the smiting.
I'll do some more in-depth testing in a few minutes now that I know it's not me needing to add something config-wise on my end.

**Comment by TheIllusiveC4** [comment]
Alright, I'll look into it then. I don't quite have access to my developer environment at the moment, but I'll check this out as soon as I'm able.

**Comment by TheIllusiveC4** [comment]
Ah right, I forgot to address your small note. The mod integration that's currently available is mostly to test functionality. In a future update, I plan to integrate them into the config so that players can choose whether or not to include them.

**Comment by IdrisQe** [comment]
ahh, okay. on that note, however, I've done further testing of all the spells in AoV, and my results were the following (note: i could have sworn none were working before but it seems i was wrong. just most.)

Caster:
Nimbus Ray - smites
Flame Strike - smites
Blade Barrier - does not smite
Searing Light - smites
Slay Living - N/A
Destruction - does not smite
Implosion - does not smite
Leap of Faith - N/A

Healer:
Cure Light Wounds - N/A
Positive Energy Burst - does not smite
Positive Energy Aura - does not smite
Cure Moderate Wounds - does not smite
Cure Poison - N/A
Cure Serious Wounds - does not smite
Cure Wither - N/A
Cure Blind - N/A
Cure Critical Wounds - does not smite
Invoke Mass - N/A
Heal - does not smite

Defender:
Aid - N/A
Shield of Faith - N/A
Zeal - N/A
Invoke Mass - N/A
Stalwart Pact - N/A

Astro:
Draw - N/A
Royal Road - N/A
Spread - N/A
Redraw - N/A
Time Dilation - N/A
Malefic - does not smite
Benefic - N/A
Combust - does not smite
Essential Dignity - N/A
Helios - N/A
Gravity - does not smite
Aspected Benefic - N/A
Celestial Opposition - N/A
Aspected Helios - N/A

**Comment by TheIllusiveC4** [comment]
It's working as intended then, since the only thing registered for AoV currently is the Nimbus Ray damage type which applies to only Nimbus Ray and Searing Light. Flame Strike works through the proxy of fire damage universally working. Like I said earlier, hopefully I'll be including some more robust config-mod integration support in future updates so this is more clearly delineated for users.
