### ISSUE TITLE
Fire Arrows unobtainable (+Suggestion)

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Consecration#20]
I'm not sure if this is intentional or not, but Fire Arrows don't seem to have a recipe as of the current release, nor in the current commit. I assume it is intentional, as they aren't in the description on Curseforge either. 
If I might make a suggestion, though... Instead of having them be craftable like most mods, it would be interesting if you had to hold a source of flame (configurable items that count) in your offhand, such as a torch or fire stick.

Maybe cause double damage to the bow when firing one too, so there's more incentive to use normal arrows for most things early-game.

Perhaps having that as a config option would be good in case people want to just craft them instead.

**Comment by TheIllusiveC4** [comment]
Actually, they should be available. I must've just forgotten. I haven't gotten around to fully updating the CurseForge description page either. I'll fix that.

I'm not sure I'm on-board with the idea of using the offhand in conjunction with the arrow like that. It just seems odd to me, and prone to accidental flame firing if the player just happens to like keeping a torch or fire stick in the offhand slot. I might be interested in having the arrow take double bow durability though.

**Comment by IdrisQe** [comment]
Fair point. 
Counterproposal: Instead of the offhand method being a config option, instead there's a keybind to use a torch, firestick, etc. from your inventory to make your next shot a fire arrow. That way they're still valuable, since they use up durability from your firestick or an entire torch per shot, but not as prone to accidental firing (pun retroactively intended). Perhaps have it be indicated by adding a flame particle effect to the draw-back animation or overlaying your fire arrow texture over the bow in the hotbar. That way people know "my next shot will be a fire arrow". Press again to blow the flaming arrow out, deactivating the fire.
Have it deactivate after a single shot, so you don't accidentally leave it on (and to simulate the time needed to light each arrow with a torch by you needing to press the hotkey each time), and after a brief period (say, 10 seconds?) it auto-deactivates (and eats an arrow because your arrow burnt too much to be  used).

Admittedly, these are probably very complicated to implement ideas, and not worth it in the long run compared to just being able to craft arrows with no config for different behaviour, etc.

**Comment by TheIllusiveC4** [comment]
That's an interesting idea, but you're right to note that it is a bit overly complicated. In addition, it's not quite in-tune with how other special arrows work, such as Tipped or Spectral Arrows, so it's a bit counter-intuitive.

**Comment by IdrisQe** [comment]
Yeah, I know. I've just always found it weird how you can hold 64 already-burning arrows in your inventory. I guess the same can be said about torches though. And buckets of lava or even molten iron that somehow don't melt the iron bucket. It's not a very realistic game.

...That does give me some mod ideas though.
