### ISSUE TITLE
Holy Armor Crashes Server on Zombie Attack

### ISSUE THREAD

**Issue by dragonshardz** [TheIllusiveC4/Consecration#22]
Player is wearing non-holy armor, zombie attacks. Server crashes.
[crash-2018-09-30_15.53.58-server.txt](https://github.com/TheIllusiveC4/Consecration/files/2432111/crash-2018-09-30_15.53.58-server.txt)

**Comment by TheIllusiveC4** [comment]
Alright, I'll get to work on a fix ASAP.

**Comment by dragonshardz** [comment]
Six minutes from bug report to assigned. That is _impressive_.
