### ISSUE TITLE
Infinite Undead Regenning

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Consecration#23]
This is a bit of an odd one, as I have no idea what the cause is. While it did only happen after I updated Consecration, I also updated a few other mods. (Although Consecration is the only likely mod that would cause this)
When undead mobs regenerate, they end up regenerating 1 extra health higher than their max, which since they're not at exactly max health, the regen effect continues on every undead mob in the area, causing lag and making everything be covered in pretty green 1s thanks to ToroHUD.
![image](https://user-images.githubusercontent.com/40530630/46282767-3fd32a00-c527-11e8-997c-4830008e8ace.png)

**Comment by TheIllusiveC4** [comment]
Hm, yeah, I think I know what's causing this. Should be an easy fix.
