### ISSUE TITLE
Low Smite Time Issues

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Consecration#24]
So I was testing lower smite times, and I noticed some odd behaviour.
If set to 1 or 2, it seems like burning mobs don't always refresh their smite effects as often as they should, so they sometimes resume regenerating health momentarily while still on fire.
In a similar vein, if set to 0 to simulate the old system, holy weapons can still damage them, but fire does not trigger the smite effect at all obviously. While that's likely intended, it would be nice to make it so burning mobs always have smite, or perhaps have a different status that makes it so they cannot regen but don't take extra damage from non-holy weapons while on fire.

**Comment by TheIllusiveC4** [comment]
While the behavior may seem odd, it seems to be functioning correctly in a sense. The smite effect is coded to damage, and fire only damages you every second or so, so there's a delay involved in this whole process. That said, I do agree that it would be counter-intuitive to have the mobs not react to being on fire so I'll change this accordingly.

**Comment by TheIllusiveC4** [comment]
I should also note that smiting from fire only lasts half as long as smiting from holy sources, which is the number you list in the config file.

**Comment by IdrisQe** [comment]
Ohhh, it may be a good idea to note that in the description for the config if you don't already. Maybe I missed it, but I wasn't aware of that. Granted since the effect gets reapplied constantly while a mob is on fire it's hard to notice.
