### ISSUE TITLE
[Suggestion] Zombie Villager Curing

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Consecration#28]
Not sure if this is implementable, but I feel this feature of Vanilla is often overlooked, and it would be perfect to integrate into this mod.
Normally to cure a Zombie Villager you need to hit them with a weakness potion and use a golden apple on them, then wait like 5 minutes. Seeing as Golden Apples aren't used in Consecration Potion recipes anymore, I was thinking that perhaps it would be nice to have Consecration potions maybe instantly start the curing process on any Zombies hit, perhaps even with half the speed, so with splash or lingering variants you could "batch cure" villager zombies after you've captured a bunch. Maybe even allow right clicking with blessed dust or a bucket/bottle of holy water to start the process (or make this a necessary step after the consecration potion so it isn't as easy as just throwing a potion and waiting)
In vanilla, Iron bars and beds reduce the curing time, so perhaps the same could be true of Holy Water and Blessed Dust placed around.

**Comment by TheIllusiveC4** [comment]
There's a different implementation of this already included actually. If everything's working right, you should be able to start the curing process for zombie villagers by dealing holy damage when they're almost dead. Although this is a remnant of the old undying mechanic and probably warrants revisiting the design. I'll keep some of your suggestions in mind and see what I can do for the next update.
