### ISSUE TITLE
Arrows of Consecration does not kill undead

### ISSUE THREAD

**Issue by 2hoo** [TheIllusiveC4/Consecration#3]
title

**Comment by TheIllusiveC4** [comment]
I can't be certain, but I think this is related to a vanilla bug where instant potion effects don't get applied due to the damage cooldown on entities. In any case, I'll try and code a workaround for this.

**Comment by TheIllusiveC4** [comment]
Okay, so it wasn't what I said before. Apparently Minecraft never checks if the potions on arrows are supposed to be instant, and assumes they're all supposed to be applied effects. I had to make the Consecration Potion work both instantaneously and as an effect over time.

TL;DR: I fixed it, and it'll be in the next update.
