### ISSUE TITLE
Shot Fire Arrow corrupted appearance

### ISSUE THREAD

**Issue by Khioni** [TheIllusiveC4/Consecration#37]
![2019-06-08_19 11 03](https://user-images.githubusercontent.com/36409872/59153173-726fe380-8a21-11e9-936e-6d398920574c.png)
Looks like the fire arrow has model issues, appearing as a floating bunch of pixels instead of an actual burning arrow. _The different fire model is from Quark, **and has nothing to do with this error**_.

Seems like it should either use the default shot arrow model (more compatible with resourcepacks, and more in line with a Flame bow) or have its own proper model (allowing for an arrowhead that looks like burning coals).

**Comment by TheIllusiveC4** [comment]
It's an intentional texture, not corruption. But I can see why it might look that way. I'm closing this issue since your other open one is more relevant since you're proposing a sprite update.

**Comment by Khioni** [comment]
Oh, so it's intentional design. Perhaps it could stand to be retouched a bit to not look like it's just a floating flame, but **that's just me**.
