### ISSUE TITLE
Further polished sprites

### ISSUE THREAD

**Issue by Khioni** [TheIllusiveC4/Consecration#38]
![fire_arrow_simple](https://user-images.githubusercontent.com/36409872/59153218-12c60800-8a22-11e9-9225-5baef082363e.png)
(Fire arrow, in a more simple style)

![fire_arrow_faithful](https://user-images.githubusercontent.com/36409872/59153221-135e9e80-8a22-11e9-8ac8-6ead19bd65fd.png)
(Fire arrow, remade while keeping the original style)

![fire_arrow_faithful_glowy](https://user-images.githubusercontent.com/36409872/59153228-66d0ec80-8a22-11e9-8ef1-4f986bb5aec9.png)
(Fire arrow, same as the above, but with a glowing outline that matches the alternate fire stick's)

![fire_stick_faithful](https://user-images.githubusercontent.com/36409872/59153219-12c60800-8a22-11e9-8784-f71919888137.png)
(Polished the Fire Stick sprite that I tweaked earlier)

![fire_stick_glowy](https://user-images.githubusercontent.com/36409872/59153220-135e9e80-8a22-11e9-8dd6-757da480f8e9.png)
(Alternate version with a glowing outline)

**Comment by TheIllusiveC4** [comment]
I think the glowing outline ones might be a bit much, but I like the second fire arrow one and the first fire stick one. I credited you in the last changelog when you made the updated fire stick sprite without really asking, but I'll ask you more formally if you'd like to be credited at all and, if so, where do you want me to do so?

**Comment by Khioni** [comment]
**Feel free to credit where you wish** - I may be freelancing it with the sprites I'm throwing around, but in the end, aren't I still contributing?

**Comment by TheIllusiveC4** [comment]
Then if it's okay with you, I'll credit you on the CurseForge project page for the textures you've contributed.

**Comment by Khioni** [comment]
That's alright.
