### ISSUE TITLE
adventurers toolbox silver weapons

### ISSUE THREAD

**Issue by SilkenStrand** [TheIllusiveC4/Consecration#4]
Would it be possible to include those as deadly? (specifically I made a sword with a silver blade, iron crossguard, leather handle, and quartz adornment. Didn't work)

Oh and while I'm trying things... Yeah silver stuff from dungeon tactics wont work either.

**Comment by TheIllusiveC4** [comment]
Thanks for reporting this. It's a known issue that silver weapons don't work even though they should. I'm working on fixing this for the next update. Specifically, I'll test out some silver weapons from Ice and Fire, Thermal Foundation, and now I'll add Adventurer's Toolbox and Dungeon Tactics to the list.
