### ISSUE TITLE
Don't working on Spongeforge-1.12.2

### ISSUE THREAD

**Issue by Jmitmax** [TheIllusiveC4/Consecration#41]
Hi, I installed the mod on spongeforge-1.12.2-2825-7.1.6 and the "Damage Reduction" function does not work on the server. The rest of the mod works without problems, but mobs die from any weapons, the config file is the same on the server and the client. If you simply install a mod on forgeserver, it works without errors.

**Comment by TheIllusiveC4** [comment]
I don't really have much experience with Sponge or SpongeForge, so I'm not sure how to evaluate or fix this. If it works fine with Forge, then it might just be an issue with SpongeForge. Regardless, I unfortunately don't plan on working on this issue on my end at this juncture.

**Comment by Jmitmax** [comment]
Ok, thanks for answering.
