### ISSUE TITLE
Error syncing field crash

### ISSUE THREAD

**Issue by Sunconure11** [TheIllusiveC4/Consecration#45]
https://paste.dimdev.org/lafimifuju.mccrash

Ran into this while testing my pack by trying to boot it up.

**Comment by TheIllusiveC4** [comment]
Seems like a result of an incorrect config file. Can you share your Consecration config settings? Or, if they're default, then try deleting and then regenerating it.

**Comment by Sunconure11** [comment]
They are default, yeah. I'll try and regen them.

**Comment by Sunconure11** [comment]
Looks like it was a faulty config.
