### ISSUE TITLE
[1.16.1-3.0] game crashes or hangs when re-entering world

### ISSUE THREAD

**Issue by bessiq** [TheIllusiveC4/Consecration#48]
#### Versions (Be specific, do not write "latest"):
* Consecration: consecration-FORGE-1.16.1-3.0.jar
* Forge: 32.0.70
#### Observed Behavior:
Game hangs or crashes when trying to re-enter a singleplayer world after saving and quitting to title. Restarting Minecraft allows you to re-enter the world, though. Tested with no other mods present.

#### Expected Behavior:
Should be able to re-enter world without restarting Minecraft.

#### Steps to Reproduce:
1. Install Forge 32.0.70 (not sure if it happened before this version)
2. Install Consecration mod (v1.16.1-3.0)
3. Create world, save & exit world, try to re-enter world

Crash Log: https://pastebin.com/h8LJg7CU

I do like this mod though. Thanks for making it!

**Comment by BedrockLegends** [comment]
I just crashed as well using this but on Forge 32.0.71
