### ISSUE TITLE
[1.12.2] Dimensional configs for mobs?

### ISSUE THREAD

**Issue by Vyraal1** [TheIllusiveC4/Consecration#5]
Would it be possible to either have GameStages integration or possibly a per dimension whitelist/blacklist that applies for the changes you made to undead mobs? I'm developing [a large pack for 1.12.2 ](https://minecraft.curseforge.com/projects/interaction) and I thought your mod was a terrific way to add progressive difficulty, especially in later tiers (which are separated by dimension.

**Comment by TheIllusiveC4** [comment]
An interesting suggestion! I've never worked with GameStages before, so I can't promise anything on that front. But I'll definitely try and add something like this. At the very least, a per dimension blacklist/whitelist config for this should be doable.
