### ISSUE TITLE
Skeletons are healing and not becoming un-empowered after being set on fire for a few seconds

### ISSUE THREAD

**Issue by celsiusqc** [TheIllusiveC4/Consecration#51]
Skeletons are healing and not becoming un-empowered after being set on fire for a few seconds
#### Versions (Be specific, do not write "latest"):
* Consecration: 4.0.0.2
* Forge: 36.0.1
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by celsiusqc** [comment]
The skeletons were spawned from a spawner*

**Comment by TheIllusiveC4** [comment]
Some follow up questions:

Did you replicate this with only Consecration installed?
Are these regular skeletons or Wither skeletons?
Can you depower them with Splash Potion of Consecration or other forms of holy damage (not fire-based)?

**Comment by celsiusqc** [comment]
> Some follow up questions:
> 
> Did you replicate this with only Consecration installed?
> Are these regular skeletons or Wither skeletons?
> Can you depower them with Splash Potion of Consecration or other forms of holy damage (not fire-based)?

the potion worked, regular skeletons, not tested with the mod alone since its on a server

**Comment by celsiusqc** [comment]
![image](https://user-images.githubusercontent.com/63996164/105125086-9292d000-5aa9-11eb-9b34-f84e259a1aed.png)
Confirmed, zombies also from spawners do not take fire consecration damage

**Comment by TheIllusiveC4** [comment]
Unfortunately I cannot reproduce this, Skeletons and Zombies from spawners take fire damage and become depowered as expected. Are your configs set so that those mobs are fire-proof? That could be a possibility. Other than that, you'd have to test this in an instance by itself otherwise I have to conclude it's a conflict with another mod.
