### ISSUE TITLE
Updating to 1.18.1

### ISSUE THREAD

**Issue by ultixon** [TheIllusiveC4/Consecration#60]
**Please describe the new feature or change.**
Basically updating the Consecration mod to 1.18.1.

**Please describe why you want this feature.**
Because this mod is the only mod (I know of) that plays around with the vanilla/modded undead mobs while making the game much harder which is something I and possibly the other 138k people enjoy.

**Comment by TheIllusiveC4** [comment]
Consecration is now available on 1.18.2. Because of the changes from 1.18.1 to 1.18.2 by Minecraft, it is not backwards compatible with 1.18.1 unfortunately.
