### ISSUE TITLE
Attach consecration to projectiles

### ISSUE THREAD

**Issue by knighthawkUnlimited** [TheIllusiveC4/Consecration#65]
Hi, I was configuring the mod and although it is quite simple to add the consecration effect to melee items such as silver swords and the like, I am finding it quiet difficult to attach it to projectiles; both splash potion and arrow type projectiles.

I first noticed it when trying to attach the effect to the 'iron crossbow bolt' from Crossbowverhaul, which I have renamed silver :) (https://www.curseforge.com/minecraft/mc-mods/crossbowverhaul).
but have also been unable to attach it to the throwing functionality of the 'silver knife' in Tools Complement (https://www.curseforge.com/minecraft/mc-mods/tools-complement), the 'silver bomb' from Galosphere (https://www.curseforge.com/minecraft/mc-mods/galosphere), as well as both the 'Glowing Water' and 'Holy Hand Grenade' from Reliquary (https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3).

I hope it's not too much trouble, and thank you for the work you have put in already :)

P.S. Tetra compat seems to be broken in 1.18 (https://www.curseforge.com/minecraft/mc-mods/tetra)

**Comment by TheIllusiveC4** [comment]
Attaching to projectiles needs to be done like this (usually):
1. Create a custom datapack in your world save
2. Create an entity type tag file located at `consecration/tags/entity_types/holy.json`
3. In this tag file, add the projectiles as entities in the `values` array. For example, adding the Holy Hand Grenade from Reliquary:

```json
{
  "replace": false,
  "values": ["reliquary:holy_hand_grenade"]
}
```

> P.S. Tetra compat seems to be broken in 1.18 (https://www.curseforge.com/minecraft/mc-mods/tetra)

Tetra integration has been re-added in the latest update.

**Comment by knighthawkUnlimited** [comment]
Hey ho, finally got around to trying your solution and it doesn't appear to be working.
I'll upload my _holy.json_ in the off chance I got something wrong, but otherwise it might just be above my skill level.

> {
  "replace": false,
  "values": ["reliquary:holy_hand_grenade",
			 "eliquary:glowing_water",
			 "crossbowverhaul:bolt_iron",
			 "tools_complement:silver_knife",
			 "galosphere:silver_bomb"]
}

Regardless, you have been a tremendous help; and thank you for your time :)

**Comment by TheIllusiveC4** [comment]
Seems to be a typo at `"eliquary:glowing_water"`. Make sure that is correct. If any of these entries are wrong, the entire tag will fail to parse.

**Comment by knighthawkUnlimited** [comment]
Thanks for catching that! :)
still not working after fixing it however.

might be emblematic of something bigger however, after some testing the projectiles in tetra aren't working either; specifically

- tomahawks
- tridents/javelins
- throwing shields
- silvered bows/crossbows

left clicking works, but with these specific weapon types it is not the only form of attack.

**Comment by TheIllusiveC4** [comment]
Do you know if your tag file is working at all? For instance, if you add `"minecraft:iron_golem"`, do their attacks deal holy damage as they should?
