### ISSUE TITLE
Undead Protection Enchantment can combined with other Protection Type Enchantments (Modded and Vanilla ones)

### ISSUE THREAD

**Issue by Maxi90909** [TheIllusiveC4/Consecration#69]
I am just going to say this right away, I am using this mod in a Modpack I created my own. IF this Issue doesn't occur for you with just forge and this mod, just mark my issue as invalid, because then my modpack is the issue and not your mod.

#### Versions (Be specific, do not write "latest"):
* Consecration:[consecration-forge-1.18.2-5.0.1.1.jar]
* Forge:1.18.2-forge-40.2.0
* 
I am currently Version 5.0.1.1 of the mod as I am wirting this issue. But after I am Done writing It I will inform you if the issue is still present in the lastest version [consecration-forge-1.18.2-5.0.1.2.jar]

#### Steps to Reproduce:
1. Enchant any type of protection on any armor pice. You can also use Undead Protection first. The order doesn't matter.
2. Then put undead protection or any other type of protection on the enchanted armor (Depending if you first enchanted the armor pice with Undead protection or any other type of proctection)

Expected Behavior: Undead Protection can't be combined with any other protection type enchantment.

Observed Behavior: Undead Protection can be combined with any other Protection type enchantment (Vanilla and modded ones)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
Game doesn't Crash. No crash report needed then?

**Comment by TheIllusiveC4** [comment]
This does seem to be a modpack issue or mod conflict, as using just Forge and Consecration the Undead Protection cannot be applied with any other protection except Feather Falling. The code is pretty straightforward in this regard as well.
